<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'General Info' => 'Informazioni Generali',
  'Security' => 'Security',
  'Fields with {*} are required.' => 'I campi con {*} sono obbligatori.',
  'Remember Me' => 'Resta loggato',
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => '&Egrave; stato richiesto un cambio di password.<br/>Non potrai loggare finch&egrave; non avrai cambiato la tua password.',
  'Access' => 'Accesso',
  'Account not active' => 'Account non attivo',
  'Activate the account' => 'Attiva l\'account',
  'An Error Occurred. Please try later.' => 'Si &egrave; verificato un errore, riprova pi&ugrave; tardi.',
  'An email was sent with the instructions to activate your account to the address {email}.' => 'Un email con i dettagli per attivare il tuo account &egrave; stata inviata all\'indirizzo {email}',
  'Approve Registration' => 'Approva la Registrazione',
  'Ban User' => 'Banna l\'utente',
  'Change Password' => 'Cambia la Password',
  'Confirm Password' => 'Conferma la Password',
  'Data Updated Succefully' => 'Dati aggiornati con successo',
  'Delete' => 'Cancella',
  'Documentation' => 'Documentazione',
  'Edit Profile' => 'Modifica il Profilo',
  'Edit {username}\'s Profile' => 'Modifica {username}',
  'Email' => 'Email',
  'Group' => 'Gruppo',
  'Group Level' => 'Livello del Gruppo',
  'Group Name' => 'Nome del Gruppo',
  'Groups' => 'Gruppi',
  'Home' => 'Home',
  'Impossible send email to the address {mail}' => 'Impossibile inviare una mail all\'indirizzo {mail}',
  'Invalid email address' => 'Indirizzo email non valido',
  'Invite User' => 'Invita un Utente',
  'Level' => 'Livello',
  'Login Required' => 'Login richiesto',
  'My Profile' => 'Mio Profilo',
  'Name' => 'Nome',
  'Old Password' => 'Vecchia Password',
  'Password' => 'Password',
  'Password Reset: Answer' => 'Reset della Password: Risposta',
  'Password Reset: Question' => 'Reset della Password: Domanda',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Inserisci le lettere mostrate nell\'immagine.<br/>Maiuscole e minuscole non sono rilevanti.',
  'Proceed' => 'Procedi',
  'Recovery Mode' => 'Recovery Mode',
  'Register' => 'Registrati',
  'Registration Complete, you can now login.' => 'Registrazione Completa, ora puoi loggare',
  'Registration Complete. You now have to wait for an admin to approve your account.' => 'Registrazione Completa. Dovrai attendere che un amministratore approvi il tuo account.',
  'Request New Password' => 'Richiedi una nuova ',
  'Resend Email' => 'Reinvia la mail',
  'Root Tools' => 'Strumenti di Root',
  'Salt' => 'Salt',
  'Save' => 'Salva',
  'The requested page does not exist.' => 'La pagina richiesta non esiste.',
  'The {messageType} Mail was succefully sent to {mail}' => 'La mail di tipo {messageType} &egrave; stata inviata a {mail}',
  'This account is not approved yet' => 'Questo account non &egrave; ancora stato approvato',
  'Update' => 'Aggiorna',
  'Update User' => 'Aggiorna l\'utente',
  'Update User Profile' => 'Aggiorna il profilo utente',
  'User Invitation' => 'Invita Utenti',
  'User List' => 'Lista Utenti',
  'User Name' => 'Nome Utente',
  'User Registration' => 'Registrazione Utente',
  'Username' => 'Nome Utente',
  'Users' => 'Utenti',
  'Verification Code' => 'Codice di Verifica',
  'We are sorry, but your account is banned' => 'Ci dispiace ma il tuo account &egrave; stato bannato',
  'You are not allowed to update other accounts' => 'Non ti &egrave; permesso modificare altri account',
  'You didn\'t enter the correct password' => 'Non hai inserito la password corretta',
  'You have succefully invited {email} to join {website}.' => 'Hai invitato {email} ad iscriversi a {website}',
  'profile' => 'profilo',
  'register' => 'iscriviti',
  'the confirmation password doesn\'t match the password' => 'la password di conferma non &egrave; uguale alla password',
  'username must be at least 4 characters and can only be alphanumeric' => 'i nomi utente devono essere di almeno 4 caratteri e possono essere solo alfanumerici',
  '{username}\'s Profile' => 'Profilo di {username}',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'la password di Root deve contenere almeno 2 lettere e due numeri',
  'the password must be of at least 5 characters' => 'la password deve essere di almeno 5 caratteri',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'la password deve contenere almeno 2 numeri e due lettere e deve essere di 5 caratteri',
  'the password must contain at least 2 digits, 2 letters and a special character' => 'la password deve avere almeno 2 numeri, 2 lettere ed un carattere speciale',
);
