<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'To Activate your account please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>' => '',
  'You have been invited to join {website}.<br/> 
					To reactivate your account and set the new password please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>
					You will be able to change the username when you activate the account' => '',
  'You requested a password reset.<br/> Your account will be disabled
				until you set a new password.<br/> To reactivate your account and set the new password please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>' => '',
  'account activation' => '',
  'invitation to {website}' => '',
  'password reset request' => '',
);
