<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.  Imposible eliminar el grupo solicitadas
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Profile Extensions' => 'Extensiones del perfil',
  'Email Customization' => 'Personalizacion de correo electrónico',
  'What\'s new?' => 'Que hay nuevo?',
  'no tooltip provided' => 'No hay ningun tooltip adquirido',
  'A problem occurred during the Data and Access Permission saving action' => 'Hubo un problema al mismo tiempo se cuenta con datos almacenados y los permisos de acceso',
  'A problem occurred during the configuration saving action' => 'Hubo un problema al mismo tiempo que se guardan las configuraciones',
  'A problem occurred during the cron jobs configuration saving action' => 'Se produjo un problema durante la acción de cron al guardar la configuración',
  'About the author' => 'Acerca del autor',
  'Ban Period' => 'Duración de la prohibición',
  'Ban Reason' => 'Motivo de la prohibición',
  'Controller' => 'controlador',
  'Cron Jobs' => 'Cron Jobs',
  'Cron Jobs Configurations Saved' => 'Configuraciones de trabajos de Cron',
  'Cron Jobs succefully removed' => 'Cron Jobs eliminado con éxito',
  'Data and Access Permission of <i>{displayname} group</i> changed' => 'Los Datos y Permisos de Acceso del <b><i>Grupo {displayname}</i></b> han sido actualizados exitosamente.',
  'Data and Access Permission of <i>{displayname} user</i> changed' => 'Los Datos y Permisos de acceso del Usuario <b><i>{displayname}</i></b> han sido actualizado exitosamente.',
  'Description' => 'Descripcion',
  'Do you really want to approve {who} registration?' => '¿Usted desea aprobar el registro de {who}?',
  'Do you really want to ban {who}?' => '¿Usted desea denegar el acceso a {who}?',
  'Do you really want to delete the group {group}?' => '¿Usted desea eliminar el {group}?',
  'Do you really want to delete the user {user}?' => '¿Usted desea eliminar el usuario {user}?',
  'Do you really want to remove those CronJobs?' => '¿Usted desea eliminar los Cron Job?',
  'Documentation' => 'Documentación',
  'Element' => 'Elemento',
  'First Steps' => 'primeros pasos',
  'Forever' => 'para siempre',
  'Group Home: {home}' => 'Grupo: principal {home}',
  'Group {groupname}: Data and Access Permissions' => 'Grupo {groupname}: De datos y permisos de acceso',
  'Impossible to delete the requested user/group. An Error Occurred' => 'Procesado',
  'Invalid Request.' => 'Solicitud no permitida',
  'Is this thing safe?' => '¿Usted cree que esto es seguro?',
  'Lapse' => 'lapso',
  'Last Execution' => 'Ultima Ejecución',
  'License' => 'Licencia',
  'Localization' => 'Localización',
  'Main Configurations' => 'Configuracion General',
  'Module' => 'Modulo',
  'New Configurations Saved' => 'Nuevas configuraciones han sido guardadas',
  'New Group: Data and Access Permissions' => 'Nuevo Grupo: Permisos de Datos y Acceso',
  'New User: Data and Access Permissions' => 'Nuevo usuario: Permisos de Datos y Acceso',
  'New group Created.' => 'Un nuevo grupo ha sido creado',
  'New user Created.' => 'Un nuevo usuario ha sido creado',
  'Options' => 'Opciones',
  'Permission' => 'Permisos',
  'Permission granted from Group' => 'Permisos otorgados del grupo',
  'Remember if you delete a Group you\'ll delete all the users that belongs to it.' => 'Recuerde que si se elimina el grupo se eliminarán todos los usuarios que pertenecen al grupo.',
  'Remove not installed CronJobs' => 'Quitar Cron Jobs no instalados',
  'Root Tools' => 'Herramientas principales',
  'Setting' => 'Ajustes',
  'Setup the new accessControlFilter' => 'Configurar el nuevo acceso del filtro de control',
  'Status' => 'Estatus',
  'The following problems occurred: {errors}' => 'Se encontraron los siguientes errores: {errors}',
  'The requested cron does not exist.' => 'El cron solicitado no existe',
  'The requested rule does not exist.' => 'La regla solicitada no existe',
  'The requested user/group does not exist and cannot be deleted.' => 'El Grupo/Usuario que solicitó no existe y no puede ser eliminado.',
  'This group does not exist' => 'Este grupo no existe',
  'User {username}: Data and Access Permissions' => 'El usuario {username}: Datos y permisos de acceso',
  'Using the new Access Rules' => 'Usando las nuevas reglas de acceso',
  'Value' => 'Valor',
  'What\'s coming next?' => 'Qué viene a continuacion?',
  'You are not allowed to change any configuration' => 'Usted no esta autorizado para cambiar ninguna configuración.',
  'You are not allowed to change the cron jobs configuration' => 'Usted no esta autorizado para cambiar ninguna configuracion de los Cron Jobs.',
  'You are not allowed to remove cron jobs' => 'Usted no esta autorizado para eliminar ningun Cron Job',
  'You cannot assign to a User a Group that has a Level equal or higher then the one you belong to' => 'Usted no puede asignar a un Usuario un Grupo que sea igual o mayor del que usted pertenece.',
  'You cannot ban a user with a level higher then yours.' => 'Usted no puede eliminar un usuario con mayor nivel aprobatorio que el suyo.',
  'You cannot change constant values' => 'Usted no puede vambiar los valores constantes',
  'You cannot change data or permissions of Root' => 'Usted no puede cambiar data o permisos de la raiz',
  'You cannot change data or permissions of a user or a group with a level higher then yours' => 'No es posible cambiar los datos o los permisos de un usuario o un grupo con un nivel más alto',
  'You cannot change the Access Permission of the Root User' => 'No se puede cambiar el permiso de acceso del usuario root',
  'You cannot create a new user or group' => 'No se puede crear un nuevo usuario o grupo',
  'You cannot delete a user/group with an higher level then yours.' => 'No se puede eliminar un usuario / grupo con un nivel más alto que el suyo.',
  'You cannot set a Group Level equal or higher then Root' => 'No se puede establecer un Grupo de Alto Nivel igual o mayor que la raíz',
  'You cannot set a Group Level equal or superior to your own' =>'No se puede establecer un nivel de grupo igual o superior a la suya',
  'You cannot set this value to a level equal or higher then your own' => 'No se puede establecer este valor a un nivel igual o mayor que su propio',
  'You didn\'t supply a valid id' => 'Usted no proporciono un ID valido',
  'You don\'t have the permissions to delete any user/group' => 'Usted no tiene la permisologia para eliminar ningun Usuario/Grupo',
  'add group' => 'Agregar grupo',
  'add user' => 'Agregar usuario',
  'if you omit the password a random one will be generated' => 'Si usted omite la contraseña, una le sera generada automaticamente.',
  'if you omit the username the user will be able to chose one when he activates the account' => 'Si usted omite el suario, el usuario estara disponible para elegir uno cuando el active la cuenta.',
  'invalid value' => 'Valor invalido',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}. allowAutoLogin se debe establecer en Verdadero para usar la autenticación basada en cookies.',
  '{n} Day|{n} Days' => '{n} Día | {n} días',
  '{n} Month|{n} Months' => '{n} Mes | {n} Meses',
  '{n} Week|{n} Weeks' => '{n} Semana | {n} Semanas',
  '{username}\'s account is banned untill {day}.' => 'El usuario {username} ha sido bloqueado hasta el dia {day}',
  '{username}\'s account is now active.' => 'El usuario {username} esta ahora activo.',
  '{what} deleted.' => '{what} Eliminar.',
);
