<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  0 => '',
  'allow everyone, even guests, to see user profiles' => 'Permitir a todos, incluso a los invitados ver los perfiles de usuario.',
  'allow user registration' => 'Permitir el registro de usuarios.',
  'if a user has on a controller admin permissions will have access to write and read pages. If he has write permissions will also have access to read pages' => 'Si un usuario tiene un controlador de permisos de administrador tendrá acceso a leer y escribir páginas. Si tiene permisos de escritura también tendrá acceso a leer las páginas.',
  'if true users just have to provide user and email to reset their password.<br/>Otherwise they will have to answer their custom question' => 'Si es Verdadero los usuarios deben dar su usuario y su correo para resetear su contraseña. <br/> De lo contrario, tendrán que responder a su pregunta personalizada.',
  'if true when a user creates an account a mail with an activation code will be sent to his email address' => 'Si es Verdadero cuando un usuario crea una cuenta un correo electrónico con un código de activación será enviado a su dirección de correo electrónico.',
  'if true when a user creates an account a user with user admin rights will have to approve the registration.<br/>If both this setting and user_need_activation are true the user will need to activate is account first and then will need the approval' => 'Si es Verdadero cuando un usuario crea una cuenta de un usuario con derechos de administrador de usuario el mismo tendrá que aprobar el registro. <br/> Si tanto esta configuración y user_need_activation son verdaderas, el usuario tendrá que activar es la primera cuenta y luego necesitará la aprobación del mismo.',
  'logged user can see other users profiles' => 'Usuarios con sesión iniciada pueden ver otros perfiles de usuarios.',
  'logged users can see the complete user list' => 'Usuarios con sesión iniciada pueden ver la lista completa de usuarios.',
  'password strength:<br/>weak: password of at least 5 characters, any character allowed.<br/>
			medium: password of at least 5 characters, must contain at least 2 digits and 2 letters.<br/>
			strong: password of at least 5 characters, must contain at least 2 digits, 2 letters and a special character.' => 'Fortaleza de las contraseñas: Débil <br/>: contraseña de al menos 5 caracteres, todos los caracteres se les permite.<br/>
  			Media: Contraseña con al menos 5 caracteres, debe contener al menos 2 digitos y 2 letras.<br/>
  			Fuerte: Contraseña con al menos 5 caracteres, debe contener al menos 2 digitos, 2 letras y caracteres especiales.',
  'the group new users automatically belong to' => 'El grupo nuevos usuarios automaticamente pertenece a',
  'userGroups version' => 'Version de los grupos de usuario',
  'users can set their own home' => 'Usuarios pueden elegir su propia pagina de inicio.',
  'users with just admin write permissions won\'t see the Main Configurations and Cron Jobs pannels' => 'Usuarios con permisos de administrador solo de escritura no podran ver las configuraciones generales y los paneles de Cron Jobs',
  'users with userGroups admin admin permission will have access to everything, just like root' => 'Grupos de usuarios a los usuarios con permiso de administrador tendrán acceso a todo, al igual que la raíz',
);
