<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'view documentation.' => 'Ver documentación.',
  'can change permission of user and groups whose group level is below his own.' => 'Puede cambiar los permisos de usuario y grupos del nivel que esta debajo del grupo al cual pertenece.',
  'can create users and groups and has all the permission of a user with user admin permissions. The level rule still apply.' => 'Puede crear usuarios y grupos que tengan todos los permisos de un usuario con permisos de administrador del usuario. Las regla de nivel aún se aplicaran.',
  'can invite other users.' => 'Puede invitar a otros usuarios.',
  'can edit other users, ban them and approve their registrations.' => 'Puede editar otros usuarios, bloquearlos y aprobar su registro.',
);
