<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Cronjob not installed' => 'Cronjob no esta instalado.',
  'No description found for the requested cron job' => 'No se encontro ninguna descripcion para el cron job solicitado.',
  'You didn\'t set the cron table name' => 'Usted no definio el cron para el nombre de la tabla.',
  'You have to provide a name for the cronjob' => 'Usted tiene que proporcionar un nombre para el cron job',
  'could not install the module. Lapse must be an integer' => 'No se pudo instalar el modulo! El lapso de tiempo debe ser un entero.',
  'delete users who have not been activated for more then 7 days' => 'Eliminar usuarios que no han sido activados en mas de 7 dias.',
  'installed and running' => 'Instalado y en funcionamiento.',
  'not installed' => 'No se pudo instalar.',
  'reactivate users whose ban period is over' => 'Reactivar usuarios cuyo periodo de bloqueo ha finalizado.',
  'the model provided is not an instance of CActiveRecord' => 'El modelo proporcionado no es una instancia de CActiveRecord',
  'the provided criteria are not an instance of CDbCriteria' => 'Los criterios proporcionados no son una instancia de CDbCriteria',
  'you didn\'t initialize che UGCron singleton' => 'Usted no puede inicializar che UGCron singleton',
  'you didn\'t provide a valid action' => 'Usted no puede proporcionar una accion valida.',
  'you didn\'t set the columns to update' => 'Usted no puede fijar las columnas para actualizar.',
);
