<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'General Info' => 'Información General',
  'Security' => 'Seguridad',
  'Fields with {*} are required.' => 'Los campos con {*} son obligatorios.',
  'Remember Me' => 'Recordarme',
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => 'Un cambio de contraseña se ha solicitado. <br/> Usted no podra acceder hasta que cambie la contraseña.',
  'Access' => 'Acceso',
  'Account not active' => 'La cuenta no está activa',
  'Activate the account' => 'Activar la cuenta',
  'An Error Occurred. Please try later.' => 'Ha ocurrido un error. Por favor, inténtelo más tarde.',
  'An email was sent with the instructions to activate your account to the address {email}.' => 'Un correo electrónico fue enviado con las instrucciones para activar su cuenta a la dirección de correo electrónico {email}',
  'Approve Registration' => 'Aprobar registro',
  'Ban User' => 'Bloquear usuario',
  'Change Password' => 'Cambiar la contraseña',
  'Confirm Password' => 'Confirmar la contraseña',
  'Data Updated Succefully' => 'Los datos han sido actualizados satisfactoriamente.',
  'Delete' => 'Borrar',
  'Documentation' => 'Documentación',
  'Edit Profile' => 'Editar perfil',
  'Edit {username}\'s Profile' => 'Editar perfil de {username} ',
  'Email' => 'Email',
  'Group' => 'Grupo',
  'Group Level' => 'Grupo de alto nivel',
  'Group Name' => 'Nombre del grupo',
  'Groups' => 'Grupos',
  'Home' => 'Inicio',
  'Impossible send email to the address {email}' => 'Es imposible enviar un correo electronico a la direccion {email}',
  'Invalid email address' => 'Dirección de correo no valida.',
  'Invite User' => 'Invitar a un usuario',
  'Level' => 'Nivel',
  'Login Required' => 'Es necesario iniciar sesión',
  'My Profile' => 'Mi perfil de usuario',
  'Name' => 'Nombre',
  'Old Password' => 'Contraseña anterior',
  'Password' => 'Contraseña',
  'Password Reset: Answer' => 'Restablecer la contraseña: Respuesta',
  'Password Reset: Question' => 'Restablecer la contraseña: Pregunta',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Por favor, introduzca las letras tal como se muestra en la imagen de arriba. <br/> Las letras no distinguen entre mayúsculas y minúsculas.',
  'Proceed' => 'Proceder',
  'Recovery Mode' => 'Modo de recuperación',
  'Register' => 'Registrarse',
  'Registration Complete, you can now login.' => 'Registro completo, ahora usted puede iniciar sesión',
  'Registration Complete. You now have to wait for an admin to approve your account.' => 'Registro completo. Ahora tiene que esperar a que un administrador apruebe su cuenta.',
  'Request New Password' => 'Solicitar una nueva contraseña ',
  'Resend Email' => 'Reenviar correo',
  'Root Tools' => 'Herramientas de Administración',
  'Salt' => 'Salir_Falta_traducir',
  'Save' => 'Guardar',
  'The requested page does not exist.' => 'La página solicitada no existe.',
  'The {messageType} Mail was succefully sent to {mail}' => 'El {messageType} correo fue enviado exitosamente a {mail}',
  'This account is not approved yet' => 'Esta cuenta no ha sido aprobada aun',
  'Update' => 'Actualizar',
  'Update User' => 'Actualizar usuario',
  'Update User Profile' => 'Actualizar perfil de usuario',
  'User Invitation' => 'Invitación de usuario',
  'User List' => 'Lista de usuarios',
  'User Name' => 'Nombre de usuario',
  'User Registration' => 'Registro de usuario',
  'Username' => 'Nombre de usuario',
  'Users' => 'Usuarios',
  'Verification Code' => 'Código de verificación',
  'We are sorry, but your account is banned' => 'Lo sentimos, pero su cuenta está bloqueada',
  'You are not allowed to update other accounts' => '',
  'You didn\'t enter the correct password' => 'You didn\'t enter the correct password',
  'You have succefully invited {email} to join {website}.' => 'Usted tiene succefully invitados {email} para unirse a {website}',
  'profile' => 'Mi Perfil',
  'register' => 'suscribir',
  'the confirmation password doesn\'t match the password' => 'La confirmación de la contraseña se \'t coincide con la contraseña',
  'username must be at least 4 characters and can only be alphanumeric' => 'nombre de usuario debe ser al menos cuatro caracteres alfanuméricos y sólo puede ser',
  '{username}\'s Profile' => '{username} perfil',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'La contraseña de root debe contener al menos dos dígitos y dos letras y tener al menos 5 caracteres',
  'the password must be of at least 5 characters' => 'La contraseña debe tener al menos 5 caracteres de',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'La contraseña debe contener al menos los dos dígitos y letras 2 y tener al menos 5 caracteres',
  'the password must contain at least 2 digits, 2 letters and a special character' => 'la contraseña debe contener al menos dos dígitos, las letras 2 y un carácter especial',
);
