<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Password Reset: Question' => 'Restablecer la contraseña: Pregunta',
  'Setting not installed. Installation abort.' => 'Configuración no se instala. abandonar la instalación',
  '<p>userGroups Installed! To continue the configuration please login</p><p>The new Controller class file has been created. Your old controller has been saved in the component folder with the name <i>_old_Controller.php</i></p>' => '"Grupos de Usuarios <p> Installed! Para continuar con la configuración por favor login </ p> El archivo de controlador de la nueva clase se ha creado. El controlador de edad se ha guardado en la carpeta de componentes con el nombre <i> _old_Controller.php </ i> </ p>',
  'Access Code' => 'Código de Acceso',
  'Error during installation. Couldn\'t create root group with id {id}' => 'Error durante la instalación. No podía \'t crear un grupo de raíz con id {id}',
  'Error during installation. Couldn\'t create root user with id {id}' => 'Error durante la instalación. No podía \'t crear un usuario root con id {id}',
  'Retype Root Password' => 'Vuelva a escribir la contraseña de root',
  'Root Email' => 'dirección de correo electrónico',
  'Root Password' => 'la contraseña de root',
  'Root User' => 'raíz del usuario',
  'The two access codes don\'t match.' => 'El código de acceso no coincide',
  'Unable to create the tables in the database. Make sure that your db user has the necessary permissions to create a new table.<br/>This release only officially support Mysql and Postgres.' => 'No se puede crear las tablas en la base de datos. Asegúrese de que el usuario db tiene los permisos necesarios para crear una nueva tabla. <br/> Esta versión sólo soporta oficialmente MySQL y Postgres',
  'Unable to write the file {path}.' => 'No se puede escribir el archivo de {path}',
  'You didn\'t correctly set the class property in the user component.<br/>Value setted: <b>{class}</b><br/>Value expected: <b>WebUserGroups</b>' => '. De que no le \'t ajustado correctamente la propiedad de clase en el componente de usuario <br/> Valor setted: <b> {class} </ b> <br/> valor esperado: <b> WebUserGroups </ b>',
  'You didn\'t set the accessCode in your config file.' => 'De que no le \'t establecer el AccessCode en su archivo de configuración',
  'for security reasons the root password must contain at least 2 digits and 2 letters' => 'por razones de seguridad la contraseña de root debe contener al menos dos dígitos y letras 2',
  'the Access Code cannot be blank' => 'el código de acceso no puede estar vacío',
  'the confirmation password doesn\'t match the password' => 'la contraseña de confirmación doesn \'t no coincide con la contraseña',
);
