<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'To Activate your account please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>' =>'Para activar su cuenta, por favor haga clic en este enlace:<br/>{full_link}
					<br/>o puede ir a esta dirección<br/>{link}<br/>e insertar en el formulario los siguientes datos<br/>nombre de usuario: <b>{username}</b>
					<br/>el código de activación: <b>{activation_code}</b><br/>',
  'You have been invited to join {website}.<br/> 
					To reactivate your account and set the new password please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>
					You will be able to change the username when you activate the account' =>  'Usted ha sido invitado a unirse a {website}.<br/> 
					Para reactivar su cuenta y establecer la nueva contraseña por favor haga clic en este enlace:<br/>{full_link}
					<br/>o puede ir a esta dirección<br/>{link}<br/>e insertar en el formulario los siguientes datos<br/>nombre del usuario: <b>{username}</b>
					<br/>codigo de activación: <b>{activation_code}</b><br/>
					Usted será capaz de cambiar el nombre de usuario cuando se activa la cuenta',
  'You requested a password reset.<br/> Your account will be disabled
				until you set a new password.<br/> To reactivate your account and set the new password please click on this link:<br/>{full_link}
					<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>' => 'La solicitud de un restablecimiento de contraseña.<br/> Su cuenta será deshabilitada
				hasta que se establezca una nueva contraseña.<br/> Para reactivar su cuenta y establecer la nueva contraseña por favor haga clic en este enlace:<br/>{full_link}
					<br/>o puede ir a esta dirección<br/>{link}<br/>e insertar en el formulario los siguientes datos<br/>nombre de usuario: <b>{username}</b>
					<br/>activation code: <b>{activation_code}</b><br/>',
  'account activation' => 'activación de la cuenta',
  'invitation to {website}' => 'invitación a {website}',
  'password reset request' => 'solicitud de restablecimiento de contraseña',
);
