<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'A mail to reset your password was sent to the address {email}.' => '"Un correo electrónico para restablecer la contraseña se ha enviado a la dirección de correo electrónico {email}',
  'Input the right answer' => 'De entrada la respuesta correcta',
  'Invalid activation code' => 'Código de activación inválido',
  'Invalid email address' => 'No válida la dirección de correo electrónico',
  'Password Recovery' => 'Recuperar Contraseña',
  'This user cannot log in recovery mode.' => 'Este usuario no puede iniciar sesión en la recuperación de la contraseña',
  'User Activation' => 'Se espera la activación del usuario',
  'Username not valid' => 'Nombre de usuario no es válido',
  'wrong user or password.' => 'Usuario o Clave incorrecta',
);
